# Generated by Django 5.2.11 on 2026-02-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapp',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='myapp',
            name='phone',
        ),
    ]
